<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0;net10.0;net11.0</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsTestProject Condition="'$(RunIntegrations)' != 'true'">false</IsTestProject>

        <EnableMSTestRunner Condition="'$(RunIntegrations)' == 'true'">true</EnableMSTestRunner>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
        <OutputType>exe</OutputType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'net11.0'">
        <Features>runtime-async=on</Features>
    </PropertyGroup>

    <PropertyGroup>
        <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    </PropertyGroup>


    <ItemGroup>
      <ProjectReference Include="..\PixivApi\PixivApi.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Playwright" Version="1.59.0" />
      <PackageReference Include="MSTest" Version="4.2.2" />
      <PackageReference Include="System.Linq.Async" Version="7.0.1" />
    </ItemGroup>

</Project>
