namespace PixivApi.Tests;

public static class UrlPayloadMapping
{
    public static Dictionary<string, string> Mapping = new Dictionary<string, string>()
    {
        {
          "https://www.pixiv.net/",
          "GetMyUserId.json"
        },
        {
            "https://www.pixiv.net/ajax/user/24367326/profile/all", 
            "GetUserAllWorks.json"
        },
        {
            "https://www.pixiv.net/ajax/user/30757805/profile/all", 
            "GetUserAllWorks-30757805.json"
        },
        {
            "https://www.pixiv.net/ajax/user/24367326?full=1",
            "GetUserInfo.json"
        },
        {
            "https://www.pixiv.net/ajax/user/24367326/profile/top",
            "GetUserTopWorks.json"
        },
        {
            "https://www.pixiv.net/ajax/illust/56099861",
            "GetIllustInfo-56099861.json"
        },
        {
            "https://www.pixiv.net/ajax/illust/57826890",
            "GetIllustInfo-57826890.json"
        },
        {
            "https://www.pixiv.net/ajax/illust/68972163/pages",
            "GetIllustPages.json"
        },
        {
            "https://www.pixiv.net/ajax/illust/49319675/ugoira_meta",
            "GetAnimateIllustMeta.json"
        },
        {
            "https://www.pixiv.net/ajax/series/236717?p=1",
            "GetMangaSeries.json"
        },
        {
            "https://www.pixiv.net/ajax/series/236717?p=2",
            "GetMangaSeriesLastPage.json"
        },
        {
            "https://www.pixiv.net/ajax/novel/23496777",
            "GetNovelInfo.json"
        },
        {
            "https://www.pixiv.net/ajax/novel/series_content/9256559?limit=30&last_order=0&order_by=asc",
            "GetNovelSeriesChapters.json"
        },
        {
            "https://www.pixiv.net/ajax/user/1/illusts/bookmarks?tag=&offset=0&limit=1&rest=hide",
            "GetUserBookmarkIllusts.json"
        },
        {
            "https://www.pixiv.net/ajax/user/1/illusts/bookmarks?tag=%E3%82%A2%E3%82%BA%E3%83%BC%E3%83%AB%E3%83%AC%E3%83%BC%E3%83%B3&offset=192&limit=48&rest=hide",
            "GetUserBookmarkIllusts.json"
        },
        {
            "https://www.pixiv.net/ajax/user/1/illusts/bookmark/tags?lang=en",
            "GetUserBookmarkIllustTags.json"
        },
        {
            "https://www.pixiv.net/ajax/illust/130220151/ugoira_meta",
            "GetUgoiraMetadata.json"
        },
        {
            "https://www.pixiv.net/ajax/search/illustrations/%E3%83%A1%E3%82%A4%E3%83%89?word=%E3%83%A1%E3%82%A4%E3%83%89&order=date_d&mode=all&p=1&csw=0&s_mode=s_tag_full&type=illust_and_ugoira&lang=en",
            "SearchIllustrations.json"
        },
        {
            "https://api.fanbox.cc/plan.listSupporting",
            "GetSupportingPlans.json"
        },
        {
            "https://api.fanbox.cc/creator.listFollowing",
            "GetFollowedCreators.json"
        },
        {
            "https://api.fanbox.cc/post.paginateCreator?creatorId=emorimiku",
            "GetCreatorPostPagination.json"
        },
        {
            "https://api.fanbox.cc/post.listCreator?creatorId=emorimiku&maxPublishedDatetime=2025-05-03%2015%3A01%3A05&maxId=9820948&limit=10",
            "GetCreatorPostsFromPagination.json"
        },
        {
            "https://api.fanbox.cc/post.info?postId=9345840",
            "GetPostInfo.json"
        }
    };
}